### PR TITLE
Region enumeration on linux & windows

### PR DESCRIPTION
**Pull request by CertainLach**
Currenly has dependence on git repo, as long as https://github.com/tinaun/gen-iter/pull/3 isn't merged

Also requires nightly for generators

### CODE REVIEW

**Comment by darfink** [comment]
Sorry for leaving you without any input.

This is definitely an interesting addition once generators are stabilised. I'm a bit torn between keeping the library simple yet providing functionality for operations that are frequent.

Functionality similar to this, is something that I already utilise in [detour-rs](/darfink/detour-rs), but it's not as straight forward when it's not integrated directly into the *region* library.

**Comment by darfink** [comment]
I've refactored the internal `query` implementation to use iterators instead, greatly inspired by this branch. It's merged in master but I've yet to release it.

It's implemented for all OSs, but Windows & Linux can be seen here:
https://github.com/darfink/region-rs/blob/02a1d48164efe9eb18adec1362fde6d72a55885a/src/os/linux.rs#L7-L26

https://github.com/darfink/region-rs/blob/02a1d48164efe9eb18adec1362fde6d72a55885a/src/os/windows.rs#L11-L55

**Comment by morrisonlevi** [comment]
I think we can close this now, right?

**Comment by CertainLach** [comment]
Yep, this is already implemented.

**Pull request closed without merging**
