### PR TITLE
netbsd implementation proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by darfink** [comment]
Thank you for this contribution! I can see it shares similarities with its FreeBSD sibling.

With that said, I will await merging this until I've setup a CI environment for NetBSD.
I expect that will be during this month.

**Comment by bsiegert** [comment]
@darfink It has been 2.5 years. Is there anything we can do to help?

**Comment by pfr-dev** [comment]
@darfink I have recently tested and can confirm this patch works on NetBSD 9.3_STABLE 
Please merge upstream. Cheers

**Comment by darfink** [comment]
Sorry. As often is the case, life gets in the way. I'll make sure to push out a new release as well.

**Pull request merged**
